export const DATE_RANGES = {
  LAST_30_DAYS: "LAST_30_DAYS",
  LAST_90_DAYS: "LAST_90_DAYS",
  LAST_180_DAYS: "LAST_180_DAYS",
  LAST_YEAR: "LAST_YEAR",
  CUSTOM: "CUSTOM",
  ALL_TIME: "ALL_TIME",
};
