export const FLUX_CATEGORIES = {
  PRODUCTOS: "PRODUCTOS",
  SERVICIO: "SERVICIO",
  ALQUILER: "ALQUILER",
  MARKETING: "MARKETING",
  MUEBLES_MAQUINAS: "MUEBLES Y MAQUINAS",
  ARREGLOS_LUGAR: "ARREGLOS DEL LUGAR",
  LEGAL: "LEGAL",
  SUELDOS: "SUELDOS",
  HERRAMIENTAS: "HERRAMIENTAS",
  TECNOLOGIA: "TECNOLOGIA",
};
