import { Request, Response } from "express";
import { QRInventoryService } from "../services/qrInventory.service";

const actor = (res: Response) => ({ id: String(res.locals.auth?.id || ""), name: String(res.locals.auth?.email || res.locals.auth?.id || "") });
const sendError = (res: Response, error: any) => res.status(400).json({ success: false, message: error?.message || "No se pudo procesar el inventario" });
export const getQRInventoryByBranch = async (req: Request, res: Response) => { try { const inventory = await QRInventoryService.getByBranch(String(req.query.sucursalId || "")); return res.json({ success: true, inventory }); } catch (error) { return sendError(res, error); } };
export const createQRInventory = async (req: Request, res: Response) => { try { const inventory = await QRInventoryService.create(String(req.body?.sucursalId || ""), actor(res)); return res.status(201).json({ success: true, inventory }); } catch (error) { return sendError(res, error); } };
export const scanQRInventory = async (req: Request, res: Response) => { try { const inventory = await QRInventoryService.scan(String(req.params.id), String(req.body?.payload || ""), actor(res)); return res.json({ success: true, inventory }); } catch (error) { return sendError(res, error); } };
export const correctQRInventory = async (req: Request, res: Response) => { try { const inventory = await QRInventoryService.correct(String(req.params.id), String(req.params.rowId), req.body?.countedStock, String(req.body?.reason || ""), actor(res)); return res.json({ success: true, inventory }); } catch (error) { return sendError(res, error); } };
export const transitionQRInventory = async (req: Request, res: Response) => { try { const status = req.body?.status; if (!["open", "paused", "closed"].includes(status)) throw new Error("Estado invalido"); const inventory = await QRInventoryService.transition(String(req.params.id), status, actor(res)); return res.json({ success: true, inventory }); } catch (error) { return sendError(res, error); } };
export const exportQRInventory = async (req: Request, res: Response) => { try { const result = await QRInventoryService.exportReport(String(req.params.id)); res.set({ "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": `attachment; filename="${result.filename}"`, "Content-Length": result.buffer.length }); return res.send(result.buffer); } catch (error) { return sendError(res, error); } };
